import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/app/ui/globals.css';
import PrelineScript from '@/app/ui/PrelineScript';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='bg-[#f6f9f8] dark:bg-[#060908]'>
      <body className={inter.className}>{children}</body>
      <PrelineScript />
    </html>
  );
}
